name: build-ubuntu-18.04

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: build
      run: |
        mkdir build
        npm install
        npm install natives@1.1.6
        gulp
        npx webpack --mode=none
        mv build TON-Wallet-Plugin
        zip -r TON-Wallet-Plugin-ubuntu-18.04.zip TON-Wallet-Plugin
        mkdir build
        cp TON-Wallet-Plugin-ubuntu-18.04.zip build

    - name: send to release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}